name: Test
on:
  workflow_dispatch:
  pull_request:
    paths: ["action.yml", ".github/workflows/test.yml"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash

env:
  PR_NUMBER: 11 # Pull request for test
  DEFAULT_CONFIG_PATH: .github/labeler.yml

jobs:
  test-configuration-path:
    name: Test for configuration-path
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Setup
        id: setup
        run: |
          set -x
          rm -f "${DEFAULT_CONFIG_PATH}"

          config="${RUNNER_TEMP}/labeler.yml"
          cat <<EOF >"${config}"
          test:
            - head-branch: ["^test", "configuration-path"]
          EOF
          echo "path=${config}" >> "${GITHUB_OUTPUT}"

      - name: Exercise
        id: exercise
        uses: ./
        with:
          configuration-path: ${{ steps.setup.outputs.path }}
          pr-number: ${{ env.PR_NUMBER }}

      - name: Verify
        env:
          CONFIGURATION_PATH: ${{ steps.exercise.outputs.configuration-path }}
          CONFIGURATION_SHA256: ${{ steps.exercise.outputs.configuration-sha256 }}
        run: |
          set -x
          test "${CONFIGURATION_PATH}" = "${RUNNER_TEMP}/labeler.yml"
          test "${CONFIGURATION_SHA256}" = "06fc2d8fa829a1a17a9be62a9f62c68532956b93fd8c5587cf5e87360f08704c"

  test-configuration-url:
    name: Test for configuration-url
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Setup
        run: |
          set -x
          rm -f "${DEFAULT_CONFIG_PATH}"

      - name: Exercise
        id: exercise
        uses: ./
        with:
          configuration-url: https://raw.githubusercontent.com/tmknom/cross-labeler-action/e23cfda6a6423ce68d3787c476e41773e07778fd/.github/fixtures/test.yml
          pr-number: ${{ env.PR_NUMBER }}

      - name: Verify
        env:
          CONFIGURATION_PATH: ${{ steps.exercise.outputs.configuration-path }}
          CONFIGURATION_SHA256: ${{ steps.exercise.outputs.configuration-sha256 }}
        run: |
          set -x
          [[ "${CONFIGURATION_PATH}" =~ "${RUNNER_TEMP}"/yamllint-.*.yml ]]
          test "${CONFIGURATION_SHA256}" = "fc22a47183b116ad92bbb2418d40cbb84d397a936701319632e1e47bfcb5b51a"

  test-omit:
    name: Test for omit
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Setup
        run: |
          set -x
          cat <<EOF >"${DEFAULT_CONFIG_PATH}"
          test:
            - head-branch: ["^test", "omit"]
          EOF

      - name: Exercise
        id: exercise
        uses: ./
        with:
          pr-number: ${{ env.PR_NUMBER }}

      - name: Verify
        env:
          CONFIGURATION_PATH: ${{ steps.exercise.outputs.configuration-path }}
          CONFIGURATION_SHA256: ${{ steps.exercise.outputs.configuration-sha256 }}
        run: |
          set -x
          test "${CONFIGURATION_PATH}" = ".github/labeler.yml"
          test "${CONFIGURATION_SHA256}" = "8d62af2e414812b4cacf959a3b70285b14fde7246f0212a2af40486c7b602b7e"

  test-error:
    name: Test for error
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Setup
        run: |
          set -x
          rm -f "${DEFAULT_CONFIG_PATH}"

      - name: Exercise
        id: exercise
        uses: ./
        with:
          pr-number: ${{ env.PR_NUMBER }}
        continue-on-error: true

      - name: Verify
        if: ${{ always() }}
        env:
          OUTCOME: ${{ steps.exercise.outcome }}
        run: |
          set -x
          test "${OUTCOME}" = "failure"
